export const MESSAGE = {
    USER_NOT_FOUND: 'User Not Found',
    USERS_FOUND_SUCCESSFULLY: 'Users Found Successfully',
    LOGIN_SUCCESSFUL: 'Login Successfully',
    INVALID_CREDENTIALS: 'Invalid credentials',
    FIELDS_REQUIRED: 'All fields are required',
    USER_ALREADY_EXITS: 'User already exists',
    USERS_DATA: 'Users data',
    USER_DETAILS_UPDATED: 'User details updated',
    USER_DELETED: 'User Deleted',
    COURSE_ALREADY_EXISTS: 'Course already exists',
    COURSE_CREATED: 'Course created successfully',
    COURSE_NOT_FOUND: 'Course not found!',
    COURSE_DATA: 'Course Found',
    COURSE_UPDATED: 'Course updated successfully',
    REQUIRED_COURSE_ID: 'Course ID is required',
    COURSE_DELETED: 'Course deleted successfully',
    COURSE_ENROLLED: 'You have enroll a course successfully',
    LESSON_NOT_FOUND: 'Lesson not found',
    LESSON_CREATED: 'Lesson Created',
    PASSWORD_RESET: 'Password reset successful',
    INVALID_TOKEN: 'Invalid or expired reset token',
    RESET_PASSWORD_EMAIL_SENT: 'Reset password email sent',
    STRIPE_PRODUCT_CREATION_FAILED: 'Stripe product creation failed',
    STRIPE_PRICE_CREATION_FAILED: 'Stripe price creation failed',
    USER_CREATED: 'User created',
    COURSE_LEFT: 'Course left successfully',
    IMAGE_UPLOAD_SUCCESS: 'Image uploaded successfully',
    LESSON_LIST: 'Lesson list',
    CERTIFICATE_DOWNLOAD: 'Certificate downloaded successfully',
    LESSON_COMPLETED: 'Lesson completed',
};
